### ISSUE TITLE
[SilentTyping][Suggestion] Per-channel silent typing

### ISSUE THREAD

**Issue by QuickNET-Tech** [WinstonSepruko/aliucord-plugins#1]
I would like a way to toggle silent typing per channel. Just a slash command like `/silenttypinghere <true|false>` would suffice, but some form of UI element that will show if silent typing is on or off in the current channel and toggles when pressed would be even better.

Main use case would be so that I can easily still show that I'm typing in DMs with certain people, e.g. I want my SO to be able to tell that I'm typing. I always forget to either turn silent typing off until I'm already well into talking to these people or just end up leaving silent typing disabled.

**Comment by WinstonSepruko** [comment]
Please recreate this issue using the new template, thank you! 

> P.S you will need to use a browser to do so if you're on mobile as the GitHub app does not yet support issue forms!
